spring:
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssh?useUnicode=true&characterEncoding=utf-8
    username: root

  mvc:
    pathmatch:
      use-suffix-pattern: false
      use-registered-suffix-pattern: true
    contentnegotiation:
      favor-path-extension: false
  session:
    store-type: redis
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
    timeout: 20000
    #jedis:
    #  pool:
    #    max-idle: 8
    #    min-idle: 0
    #    max-active: 8
    #    max-wait: -1

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.jk.model
