spring:
  #redis连接池信息
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 20000
    database: 0
    #配置哨兵集群
    sentinel:
      master: mymaster
      nodes: 192.168.2.132:26379,192.168.2.132:26380,192.168.2.132:26381
    cluster:
      #配置redis集群
      nodes: 192.168.2.132:6379,192.168.2.132:6380,192.168.2.132:6381
server:
  port: 8088
